### ISSUE TITLE
Design review for VGPU_type identifiers

### ISSUE THREAD

**Issue by johnelse** [xapi-project/xapi-project.github.io#156]
Design at https://xapi-project.github.io/xapi/futures/vgpu-type-identifiers.html

**Comment by robhoes** [comment]
Looks good. It reminds me of the `GPU_group.GPU_types` field, which is used when PGPUs are discovered, to determine which group to put them in. IIRC, I initially wanted to make that field `internal_only` (just to make it a little easier to change the format later), but couldn't because the import code needed it explicitly. Does the same apply to `VGPU_type.identifier`, or can it be made internal?

**Comment by johnelse** [comment]
Yes, it is a similar idea to `GPU_group.GPU_types`. And yes, VGPU_type.identifier also needs to be available for the import code to use :-)

**Comment by robhoes** [comment]
OK, let's have it this way then :) 
It'd be good to note in the API doc string that the contents of the field shouldn't be interpreted by clients (or something like that).

**Comment by johnelse** [comment]
Indeed, I'll note that.

**Comment by johnelse** [comment]
:shipit:
